### PR TITLE
User favorites page

### PR DESCRIPTION
**Pull request by DariBerrie**
added a very basic user favorites page that is set up in the products controller as well with a collection route.
Screen Shot 2023-03-02 at 18 08 11

### CODE REVIEW

**Comment by fservignat** [comment]
Looks good, I'm not sure what's left to do on my end now
Toggle icon + auto update fav page and routes?

**Review by fservignat — APPROVED** [review]

**Comment by DariBerrie** [comment]
@fservignat This was just a mockup so that you would have a page to work from. You can implement the page & card design as you wish :)

**Comment by fservignat** [comment]
I try to work on it but I'm still stuck with the barcode reader. It doesnt find any product, and even when I put a raise, it doesnt detect it. I can't work on it if I dont have access to the product show, and so in the user_favorite page I dont have any product appearing either. It's really frustrating. I'll continue to try to find a solution

**Comment by DariBerrie** [comment]
Can you Google the sessions error you have in your console? It might
provide some clues as to what is happening on your machine.

**Comment by fservignat** [comment]
How do you get that view in products/user_favorites ? Do you use the camera to scan the product or use the bar code ? Then do you click on the "add to favorite" and get directed to the products/user_favorites and the product is there? I found that I should use the barcode without the 0 at the beginning like '769915191004', but it still doesnt work.

**Pull request merged**
