### PR TITLE
User is asked to log in to save a product and redirected to product page

### PR DESCRIPTION
**Pull request by simonabar1**
- User now needs to be logged in or signed up to save a product;
- After log in, they are redirected to the same product page
- Styled the sign in / sign up pages and social login buttons
Screenshot 2023-02-26 at 10 46 26
Screenshot 2023-02-26 at 10 46 41
Screenshot 2023-02-26 at 11 14 13
Screenshot 2023-02-26 at 11 14 21
6b9db1.png)

### CODE REVIEW

**Comment by DariBerrie** [comment]
This looks very cool! And I'm glad we have more "official" sign up/login buttons for the Google and Facebook authentication! Should we have an option to sign up with these services as well (not just logging in?) or does this require being a verified developer/app?

**Comment by simonabar1** [comment]
@DariBerrie  the first time a user logs in with Facebook or Google it will work as a sign up and ask for specific authorisation ("Facebook is requesting to access this info: email address" kind of message). Every other time it will just sign them up. I will update the buttons accordingly so it's more clear!

It also looks like the provider/uid fields of the schema are no longer where they are supposed to be, so this won't work. I will fix it quickly and push the code again!

**Comment by simonabar1** [comment]
Updated pages + db so everything should work.

I might need to authorise your email addresses for testing in my google/fb developer console. If you get a 'not authorised' message, let me know!

Screenshot 2023-02-27 at 15 27 00

Screenshot 2023-02-27 at 15 27 07

**Comment by DariBerrie** [comment]
Yeah, I think this makes more sense! Easy fix, but I don't think there will be any added confusion.

**Review by DariBerrie — APPROVED** [review]

**Comment by simonabar1** [comment]
Thanks Dari! Can I go ahead and merge this?

**Comment by DariBerrie** [comment]
Yep! The code looks good!

**Pull request merged**
